# Generated by Django 4.1.12 on 2024-02-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FNB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=50)),
                ("located_in", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=17, null=True)),
                ("google_map_url", models.URLField(blank=True, null=True)),
                ("menu_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("order_url", models.URLField(blank=True, null=True)),
                (
                    "company_brand_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "halal_certification_expiry_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "halal_certification_body",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("reviews_count", models.IntegerField(default=0)),
                ("photos_count", models.IntegerField(default=0)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("text", models.TextField(blank=True, null=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                (
                    "fnb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="home.fnb",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="home.reviewer",
                    ),
                ),
            ],
        ),
    ]
