# Generated by Django 4.1.12 on 2024-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnb',
            name='category',
        ),
        migrations.AddField(
            model_name='fnb',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
