# Generated by Django 4.1.12 on 2024-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_fnb_category_fnb_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnb',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
