# Generated by Django 4.1.12 on 2024-02-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fnb_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnb',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
